[workspace]
members = [
    "contracts/escrow",
    "contracts/reputation",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "26.1.0" }

[profile.release]
codegen-units = 1
debug = "line-tables-only"
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
strip = "symbols"

[profile.release-with-logs]
inherits = "release"
debug = true
strip = "none"
